function player_load(){
    if(year_v==0){ //1990년
        title=ninezero[rank_v];
        u_src=ninezero_u[rank_v];
        document.getElementById('audio').src='audio/1990/'+title+'.mp3';
        audio.load();
        //aud.src='audio/1990/'+title+'.mp3';
        //aud.load();
    }
    if(year_v==1){ //1991년
        title=nineone[rank_v];
        u_src=nineone_u[rank_v];
        document.getElementById('audio').src='audio/1991/'+title+'.mp3';
        audio.load();
    }
    if(year_v==2){ //1992년
        title=ninetwo[rank_v];
        u_src=ninetwo_u[rank_v];
        document.getElementById('audio').src='audio/1992/'+title+'.mp3';
        audio.load();
    }
    if(year_v==3){ //1993년
        title=ninethree[rank_v];
        u_src=ninethree_u[rank_v];
        document.getElementById('audio').src='audio/1993/'+title+'.mp3';
        audio.load();
    }
    if(year_v==4){ //1994년
        title=ninefour[rank_v];
        u_src=ninefour_u[rank_v];
        document.getElementById('audio').src='audio/1994/'+title+'.mp3';
        audio.load();
    }
    if(year_v==5){ //1995년
        title=ninefive[rank_v];
        u_src=ninefive_u[rank_v];
        document.getElementById('audio').src='audio/1995/'+title+'.mp3';
        audio.load();
    }
    if(year_v==6){ //1996년
        title=ninesix[rank_v];
        u_src=ninesix_u[rank_v];
        document.getElementById('audio').src='audio/1996/'+title+'.mp3';
        audio.load();
    }
    if(year_v==7){ //1997년
        title=nineseven[rank_v];
        u_src=nineseven_u[rank_v];
        document.getElementById('audio').src='audio/1997/'+title+'.mp3';
        audio.load();
    }
    if(year_v==8){ //1998년
        title=nineeight[rank_v];
        u_src=nineeight_u[rank_v];
        document.getElementById('audio').src='audio/1998/'+title+'.mp3';
        audio.load();
    }
    if(year_v==9){ //1999년
        title=ninenine[rank_v];
        u_src=ninenine_u[rank_v];
        document.getElementById('audio').src='audio/1999/'+title+'.mp3';
        audio.load();
    }
    if(year_v==10){ //2000년
        title=zerozero[rank_v];
        u_src=zerozero_u[rank_v];
        document.getElementById('audio').src='audio/2000/'+title+'.mp3';
        audio.load();
    }
    if(year_v==11){ //2001년
        title=zeroone[rank_v];
        u_src=zeroone_u[rank_v];
        document.getElementById('audio').src='audio/2001/'+title+'.mp3';
        audio.load();
    }
    if(year_v==12){ //2002년
        title=zerotwo[rank_v];
        u_src=zerotwo_u[rank_v];
        document.getElementById('audio').src='audio/2002/'+title+'.mp3';
        audio.load();
    }
    if(year_v==13){ //2003년
        title=zerothree[rank_v];
        u_src=zerothree_u[rank_v];
        document.getElementById('audio').src='audio/2003/'+title+'.mp3';
        audio.load();
    }
    if(year_v==14){ //2004년
        title=zerofour[rank_v];
        u_src=zerofour_u[rank_v];
        document.getElementById('audio').src='audio/2004/'+title+'.mp3';
        audio.load();
    }
    if(year_v==15){ //2005년
        title=zerofive[rank_v];
        u_src=zerofive_u[rank_v];
        document.getElementById('audio').src='audio/2005/'+title+'.mp3';
        audio.load();
    }
    if(year_v==16){ //2006년
        title=zerosix[rank_v];
        u_src=zerosix_u[rank_v];
        document.getElementById('audio').src='audio/2006/'+title+'.mp3';
        audio.load();
    }
    if(year_v==17){ //2007년
        title=zeroseven[rank_v];
        u_src=zeroseven_u[rank_v];
        document.getElementById('audio').src='audio/2007/'+title+'.mp3';
        audio.load();
    }
    if(year_v==18){ //2008년
        title=zeroeight[rank_v];
        u_src=zeroeight_u[rank_v];
        document.getElementById('audio').src='audio/2008/'+title+'.mp3';
        audio.load();
    }
    if(year_v==19){ //2009년
        title=zeronine[rank_v];
        u_src=zeronine_u[rank_v];
        document.getElementById('audio').src='audio/2009/'+title+'.mp3';
        audio.load();
    }
    if(year_v==20){ //2010년
        title=onezero[rank_v];
        u_src=onezero_u[rank_v];
        document.getElementById('audio').src='audio/2010/'+title+'.mp3';
        audio.load();
    }
    if(year_v==21){ //2011년
        title=oneone[rank_v];
        u_src=oneone_u[rank_v];
        document.getElementById('audio').src='audio/2011/'+title+'.mp3';
        audio.load();
    }
    if(year_v==22){ //2012년
        title=onetwo[rank_v];
        u_src=onetwo_u[rank_v];
        document.getElementById('audio').src='audio/2012/'+title+'.mp3';
        audio.load();
    }
    if(year_v==23){ //2013년
        title=onethree[rank_v];
        u_src=onethree_u[rank_v];
        document.getElementById('audio').src='audio/2013/'+title+'.mp3';
        audio.load();
    }
    if(year_v==24){ //2014년
        title=onefour[rank_v];
        u_src=onefour_u[rank_v];
        document.getElementById('audio').src='audio/2014/'+title+'.mp3';
        audio.load();
    }
    if(year_v==25){ //2015년
        title=onefive[rank_v];
        u_src=onefive_u[rank_v];
        document.getElementById('audio').src='audio/2015/'+title+'.mp3';
        audio.load();
    }
    if(year_v==26){ //2016년
        title=onesix[rank_v];
        u_src=onesix_u[rank_v];
        document.getElementById('audio').src='audio/2016/'+title+'.mp3';
        audio.load();
    }
    if(year_v==27){ //2017년
        title=oneseven[rank_v];
        u_src=oneseven_u[rank_v];
        document.getElementById('audio').src='audio/2017/'+title+'.mp3';
        audio.load();
    }
    if(year_v==28){ //2018년
        title=oneeight[rank_v];
        u_src=oneeight_u[rank_v];
        document.getElementById('audio').src='audio/2018/'+title+'.mp3';
        audio.load();
    }
    if(year_v==29){ //2019년
        title=onenine[rank_v];
        u_src=onenine_u[rank_v];
        document.getElementById('audio').src='audio/2019/'+title+'.mp3';
        audio.load();
    }
    if(year_v==30){ //2020년
        title=current[rank_v];
        u_src=current_u[rank_v];
        document.getElementById('audio').src='audio/2020/'+title+'.mp3';
        audio.load();
    }
    /*if(year_v==0){ //1990년
        title=ninezero[rank_v];
        //document.getElementById('audio').src='audio/1990/'+title+'.mp3';
        //audio.load();
        aud.src='audio/1990/'+title+'.mp3';
        aud.load();
    }
    if(year_v==1){ //1991년
        title=nineone[rank_v];
        //document.getElementById('audio').src='audio/1991/'+title+'.mp3';
        aud.src='audio/1991/'+title+'.mp3';
        aud.load();
    }
    if(year_v==2){ //1992년
        title=ninetwo[rank_v];
        //document.getElementById('audio').src='audio/1992/'+title+'.mp3';
        aud.src='audio/1992/'+title+'.mp3';
        aud.load();
    }
    if(year_v==3){ //1993년
        title=ninethree[rank_v];
        //document.getElementById('audio').src='audio/1993/'+title+'.mp3';
        aud.src='audio/1993/'+title+'.mp3';
        aud.load();
    }
    if(year_v==4){ //1994년
        title=ninefour[rank_v];
        //document.getElementById('audio').src='audio/1994/'+title+'.mp3';
        aud.src='audio/1994/'+title+'.mp3';
        aud.load();
    }
    if(year_v==5){ //1995년
        title=ninefive[rank_v];
        //document.getElementById('audio').src='audio/1995/'+title+'.mp3';
        aud.src='audio/1995/'+title+'.mp3';
        aud.load();
    }
    if(year_v==6){ //1996년
        title=ninesix[rank_v];
        //document.getElementById('audio').src='audio/1996/'+title+'.mp3';
        aud.src='audio/1996/'+title+'.mp3';
        aud.load();
    }
    if(year_v==7){ //1997년
        title=nineseven[rank_v];
        //document.getElementById('audio').src='audio/1997/'+title+'.mp3';
        aud.src='audio/1997/'+title+'.mp3';
        aud.load();
    }
    if(year_v==8){ //1998년
        title=nineeight[rank_v];
        //document.getElementById('audio').src='audio/1998/'+title+'.mp3';
        aud.src='audio/1998/'+title+'.mp3';
        aud.load();
    }
    if(year_v==9){ //1999년
        title=ninenine[rank_v];
        //document.getElementById('audio').src='audio/1999/'+title+'.mp3';
        aud.src='audio/1999/'+title+'.mp3';
        aud.load();
    }
    if(year_v==10){ //2000년
        title=zerozero[rank_v];
        //document.getElementById('audio').src='audio/2000/'+title+'.mp3';
        aud.src='audio/2000/'+title+'.mp3';
        aud.load();
    }
    if(year_v==11){ //2001년
        title=zeroone[rank_v];
        //document.getElementById('audio').src='audio/2001/'+title+'.mp3';
        aud.src='audio/2001/'+title+'.mp3';
        aud.load();
    }
    if(year_v==12){ //2002년
        title=zerotwo[rank_v];
        //document.getElementById('audio').src='audio/2002/'+title+'.mp3';
        aud.src='audio/2002/'+title+'.mp3';
        aud.load();
    }
    if(year_v==13){ //2003년
        title=zerothree[rank_v];
        //document.getElementById('audio').src='audio/2003/'+title+'.mp3';
        aud.src='audio/2003/'+title+'.mp3';
        aud.load();
    }
    if(year_v==14){ //2004년
        title=zerofour[rank_v];
        //document.getElementById('audio').src='audio/2004/'+title+'.mp3';
        aud.src='audio/2004/'+title+'.mp3';
        aud.load();
    }
    if(year_v==15){ //2005년
        title=zerofive[rank_v];
        //document.getElementById('audio').src='audio/2005/'+title+'.mp3';
        aud.src='audio/2005/'+title+'.mp3';
        aud.load();
    }
    if(year_v==16){ //2006년
        title=zerosix[rank_v];
        //document.getElementById('audio').src='audio/2006/'+title+'.mp3';
        aud.src='audio/2006/'+title+'.mp3';
        aud.load();
    }
    if(year_v==17){ //2007년
        title=zeroseven[rank_v];
        //document.getElementById('audio').src='audio/2007/'+title+'.mp3';
        aud.src='audio/2007/'+title+'.mp3';
        aud.load();
    }
    if(year_v==18){ //2008년
        title=zeroeight[rank_v];
        //document.getElementById('audio').src='audio/2008/'+title+'.mp3';
        aud.src='audio/2008/'+title+'.mp3';
        aud.load();
    }
    if(year_v==19){ //2009년
        title=zeronine[rank_v];
        //document.getElementById('audio').src='audio/2009/'+title+'.mp3';
        aud.src='audio/2009/'+title+'.mp3';
        aud.load();
    }
    if(year_v==20){ //2010년
        title=onezero[rank_v];
        //document.getElementById('audio').src='audio/2010/'+title+'.mp3';
        aud.src='audio/2010/'+title+'.mp3';
        aud.load();
    }
    if(year_v==21){ //2011년
        title=oneone[rank_v];
        //document.getElementById('audio').src='audio/2011/'+title+'.mp3';
        aud.src='audio/2011/'+title+'.mp3';
        aud.load();
    }
    if(year_v==22){ //2012년
        title=onetwo[rank_v];
        //document.getElementById('audio').src='audio/2012/'+title+'.mp3';
        aud.src='audio/2012/'+title+'.mp3';
        aud.load();
    }
    if(year_v==23){ //2013년
        title=onethree[rank_v];
        //document.getElementById('audio').src='audio/2013/'+title+'.mp3';
        aud.src='audio/2013/'+title+'.mp3';
        aud.load();
    }
    if(year_v==24){ //2014년
        title=onefour[rank_v];
        //document.getElementById('audio').src='audio/2014/'+title+'.mp3';
        aud.src='audio/2014/'+title+'.mp3';
        aud.load();
    }
    if(year_v==25){ //2015년
        title=onefive[rank_v];
        //document.getElementById('audio').src='audio/2015/'+title+'.mp3';
        aud.src='audio/2015/'+title+'.mp3';
        aud.load();
    }
    if(year_v==26){ //2016년
        title=onesix[rank_v];
        //document.getElementById('audio').src='audio/2016/'+title+'.mp3';
        aud.src='audio/2016/'+title+'.mp3';
        aud.load();
    }
    if(year_v==27){ //2017년
        title=oneseven[rank_v];
        //document.getElementById('audio').src='audio/2017/'+title+'.mp3';
        aud.src='audio/2017/'+title+'.mp3';
        aud.load();
    }
    if(year_v==28){ //2018년
        title=oneeight[rank_v];
        //document.getElementById('audio').src='audio/2018/'+title+'.mp3';
        aud.src='audio/2018/'+title+'.mp3';
        aud.load();
    }
    if(year_v==29){ //2019년
        title=onenine[rank_v];
        //document.getElementById('audio').src='audio/2019/'+title+'.mp3';
        aud.src='audio/2019/'+title+'.mp3';
        aud.load();
    }
    if(year_v==30){ //2020년
        title=current[rank_v];
        //document.getElementById('audio').src='audio/2020/'+title+'.mp3';
        aud.src='audio/2020/'+title+'.mp3';
        aud.load();
    }*/
}
//오답용
function err_load(){
    //첫번째 오답
    if(err1_year_v==0){ //1990년
    err1_title=ninezero[err1_rank_v];
    }
    if(err1_year_v==1){ //1991년
    err1_title=nineone[err1_rank_v];
    }
    if(err1_year_v==2){ //1992년
    err1_title=ninetwo[err1_rank_v];
    }
    if(err1_year_v==3){ //1993년
    err1_title=ninethree[err1_rank_v];
    }
    if(err1_year_v==4){ //1994년
    err1_title=ninefour[err1_rank_v];
    }
    if(err1_year_v==5){ //1995년
    err1_title=ninefive[err1_rank_v];
    }
    if(err1_year_v==6){ //1996년
    err1_title=ninesix[err1_rank_v];
    }
    if(err1_year_v==7){ //1997년
    err1_title=nineseven[err1_rank_v];
    }
    if(err1_year_v==8){ //1998년
    err1_title=nineeight[err1_rank_v];
    }
    if(err1_year_v==9){ //1999년
    err1_title=ninenine[err1_rank_v];
    }
    if(err1_year_v==10){ //2000년
    err1_title=zerozero[err1_rank_v];
    }
    if(err1_year_v==11){ //2001년
    err1_title=zeroone[err1_rank_v];
    }
    if(err1_year_v==12){ //2002년
    err1_title=zerotwo[err1_rank_v];
    }
    if(err1_year_v==13){ //2003년
    err1_title=zerothree[err1_rank_v];
    }
    if(err1_year_v==14){ //2004년
    err1_title=zerofour[err1_rank_v];
    }
    if(err1_year_v==15){ //2005년
    err1_title=zerofive[err1_rank_v];
    }
    if(err1_year_v==16){ //2006년
    err1_title=zerosix[err1_rank_v];
    }
    if(err1_year_v==17){ //2007년
    err1_title=zeroseven[err1_rank_v];
    }
    if(err1_year_v==18){ //2008년
    err1_title=zeroeight[err1_rank_v];
    }
    if(err1_year_v==19){ //2009년
    err1_title=zeronine[err1_rank_v];
    }
    if(err1_year_v==20){ //2010년
    err1_title=onezero[err1_rank_v];
    }
    if(err1_year_v==21){ //2011년
    err1_title=oneone[err1_rank_v];
    }
    if(err1_year_v==22){ //2012년
    err1_title=onetwo[err1_rank_v];
    }
    if(err1_year_v==23){ //2013년
    err1_title=onethree[err1_rank_v];
    }
    if(err1_year_v==24){ //2014년
    err1_title=onefour[err1_rank_v];
    }
    if(err1_year_v==25){ //2015년
    err1_title=onefive[err1_rank_v];
    }
    if(err1_year_v==26){ //2016년
    err1_title=onesix[err1_rank_v];
    }
    if(err1_year_v==27){ //2017년
    err1_title=oneseven[err1_rank_v];
    }
    if(err1_year_v==28){ //2018년
    err1_title=oneeight[err1_rank_v];
    }
    if(err1_year_v==29){ //2019년
    err1_title=onenine[err1_rank_v];
    }
    if(err1_year_v==30){ //2020년
    err1_title=current[err1_rank_v];
    }
    //두번째 오답
    if(err2_year_v==0){ //1990년
    err2_title=ninezero[err2_rank_v];
    }
    if(err2_year_v==1){ //1991년
    err2_title=nineone[err2_rank_v];
    }
    if(err2_year_v==2){ //1992년
    err2_title=ninetwo[err2_rank_v];
    }
    if(err2_year_v==3){ //1993년
    err2_title=ninethree[err2_rank_v];
    }
    if(err2_year_v==4){ //1994년
    err2_title=ninefour[err2_rank_v];
    }
    if(err2_year_v==5){ //1995년
    err2_title=ninefive[err2_rank_v];
    }
    if(err2_year_v==6){ //1996년
    err2_title=ninesix[err2_rank_v];
    }
    if(err2_year_v==7){ //1997년
    err2_title=nineseven[err2_rank_v];
    }
    if(err2_year_v==8){ //1998년
    err2_title=nineeight[err2_rank_v];
    }
    if(err2_year_v==9){ //1999년
    err2_title=ninenine[err2_rank_v];
    }
    if(err2_year_v==10){ //2000년
    err2_title=zerozero[err2_rank_v];
    }
    if(err2_year_v==11){ //2001년
    err2_title=zeroone[err2_rank_v];
    }
    if(err2_year_v==12){ //2002년
    err2_title=zerotwo[err2_rank_v];
    }
    if(err2_year_v==13){ //2003년
    err2_title=zerothree[err2_rank_v];
    }
    if(err2_year_v==14){ //2004년
    err2_title=zerofour[err2_rank_v];
    }
    if(err2_year_v==15){ //2005년
    err2_title=zerofive[err2_rank_v];
    }
    if(err2_year_v==16){ //2006년
    err2_title=zerosix[err2_rank_v];
    }
    if(err2_year_v==17){ //2007년
    err2_title=zeroseven[err2_rank_v];
    }
    if(err2_year_v==18){ //2008년
    err2_title=zeroeight[err2_rank_v];
    }
    if(err2_year_v==19){ //2009년
    err2_title=zeronine[err2_rank_v];
    }
    if(err2_year_v==20){ //2010년
    err2_title=onezero[err2_rank_v];
    }
    if(err2_year_v==21){ //2011년
    err2_title=oneone[err2_rank_v];
    }
    if(err2_year_v==22){ //2012년
    err2_title=onetwo[err2_rank_v];
    }
    if(err2_year_v==23){ //2013년
    err2_title=onethree[err2_rank_v];
    }
    if(err2_year_v==24){ //2014년
    err2_title=onefour[err2_rank_v];
    }
    if(err2_year_v==25){ //2015년
    err2_title=onefive[err2_rank_v];
    }
    if(err2_year_v==26){ //2016년
    err2_title=onesix[err2_rank_v];
    }
    if(err2_year_v==27){ //2017년
    err2_title=oneseven[err2_rank_v];
    }
    if(err2_year_v==28){ //2018년
    err2_title=oneeight[err2_rank_v];
    }
    if(err2_year_v==29){ //2019년
    err2_title=onenine[err2_rank_v];
    }
    if(err2_year_v==30){ //2020년
    err2_title=current[err2_rank_v];
    }

    if(err3_year_v==0){ //1990년
    err3_title=ninezero[err3_rank_v];
    }
    if(err3_year_v==1){ //1991년
    err3_title=nineone[err3_rank_v];
    }
    if(err3_year_v==2){ //1992년
    err3_title=ninetwo[err3_rank_v];
    }
    if(err3_year_v==3){ //1993년
    err3_title=ninethree[err3_rank_v];
    }
    if(err3_year_v==4){ //1994년
    err3_title=ninefour[err3_rank_v];
    }
    if(err3_year_v==5){ //1995년
    err3_title=ninefive[err3_rank_v];
    }
    if(err3_year_v==6){ //1996년
    err3_title=ninesix[err3_rank_v];
    }
    if(err3_year_v==7){ //1997년
    err3_title=nineseven[err3_rank_v];
    }
    if(err3_year_v==8){ //1998년
    err3_title=nineeight[err3_rank_v];
    }
    if(err3_year_v==9){ //1999년
    err3_title=ninenine[err3_rank_v];
    }
    if(err3_year_v==10){ //2000년
    err3_title=zerozero[err3_rank_v];
    }
    if(err3_year_v==11){ //2001년
    err3_title=zeroone[err3_rank_v];
    }
    if(err3_year_v==12){ //2002년
    err3_title=zerotwo[err3_rank_v];
    }
    if(err3_year_v==13){ //2003년
    err3_title=zerothree[err3_rank_v];
    }
    if(err3_year_v==14){ //2004년
    err3_title=zerofour[err3_rank_v];
    }
    if(err3_year_v==15){ //2005년
    err3_title=zerofive[err3_rank_v];
    }
    if(err3_year_v==16){ //2006년
    err3_title=zerosix[err3_rank_v];
    }
    if(err3_year_v==17){ //2007년
    err3_title=zeroseven[err3_rank_v];
    }
    if(err3_year_v==18){ //2008년
    err3_title=zeroeight[err3_rank_v];
    }
    if(err3_year_v==19){ //2009년
    err3_title=zeronine[err3_rank_v];
    }
    if(err3_year_v==20){ //2010년
    err3_title=onezero[err3_rank_v];
    }
    if(err3_year_v==21){ //2011년
    err3_title=oneone[err3_rank_v];
    }
    if(err3_year_v==22){ //2012년
    err3_title=onetwo[err3_rank_v];
    }
    if(err3_year_v==23){ //2013년
    err3_title=onethree[err3_rank_v];
    }
    if(err3_year_v==24){ //2014년
    err3_title=onefour[err3_rank_v];
    }
    if(err3_year_v==25){ //2015년
    err3_title=onefive[err3_rank_v];
    }
    if(err3_year_v==26){ //2016년
    err3_title=onesix[err3_rank_v];
    }
    if(err3_year_v==27){ //2017년
    err3_title=oneseven[err3_rank_v];
    }
    if(err3_year_v==28){ //2018년
    err3_title=oneeight[err3_rank_v];
    }
    if(err3_year_v==29){ //2019년
    err3_title=onenine[err3_rank_v];
    }
    if(err3_year_v==30){ //2020년
    err3_title=current[err3_rank_v];
    }
}